# Configuração de Experimento: Avaliação Comparativa de Modelos de Embedding (Somente Recuperação/Retrieval)
experiment_name: "compare_embeddings_retrieval_all-MiniLM"
pipeline_type: "standard_rag"

run_flags:
  generate_vector_db: false
  run_retrieval: true
  run_generation: false
  run_evaluation: true

models:
  embedding_model: "sentence-transformers/all-MiniLM-L6-v2"
  generation_llm: "gemma-4-26b-a4b-it"                     # Não será executado pois run_generation está falso
  judge_llm: "gemini-3.1-flash-lite"

# Coleção ChromaDB correspondente ao modelo de embedding selecionado
chroma_collection: "bulas" 
chroma_path: "./chroma_bulas"

datasets:
  # - "dataset/dificeis_revisadas.csv"
  - "dataset/medias_revisadas.csv"
  - "dataset/faceis_revisadas.csv"

metrics:
  section_retrieval:
    - "precision"
    - "recall"
    - "f1_score"
  corpus_coverage: true
  chunks_retrieval:
    - "Recall@K"
    - "Evidence Set Recall"
    - "MRR@K"
    - "nDCG@K"

